<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CA1416;CS8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../Models/*.cs;../../Localization/*.cs;../../Parsing/*.cs;../../Storage/*.cs;../../Services/*.cs;../../Services/Privileged/*.cs;../../UI/WindowResize.cs;../../UI/Controls/SliderRange.cs" Exclude="../../Services/TrafficMonitor.cs" />
  </ItemGroup>

</Project>
