<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>Tunnelka</AssemblyName>
    <RootNamespace>Tunnelka</RootNamespace>
    <Version>1.0.6</Version>
    <ApplicationIcon>Assets\tunnelka.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**" />
    <None Remove="tests\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="core\**" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Assets\**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="THIRD-PARTY-NOTICES.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
