namespace Tunnelka;

public static class L
{
    public static bool English { get; private set; }

    public static void Use(string language) => English = language == "en";

    public static string T(string russian) =>
        English && En.TryGetValue(russian, out var english) ? english : russian;

    public static string F(string russian, params object[] args) => string.Format(T(russian), args);

    private static readonly Dictionary<string, string> En = new()
    {
        ["/с"] = "/s",
        ["Б"] = "B",
        ["КБ"] = "KB",
        ["МБ"] = "MB",
        ["ГБ"] = "GB",
        ["ТБ"] = "TB",
        ["{0} с"] = "{0} s",
        ["{0} мин"] = "{0} min",
        ["{0} ч"] = "{0} h",
        ["3 мин"] = "3 min",
        ["10 мин"] = "10 min",
        ["30 мин"] = "30 min",
        ["1 ч"] = "1 h",
        ["3 ч"] = "3 h",
        ["5 ч"] = "5 h",
        ["24 ч"] = "24 h",
        ["Всё"] = "All",
        ["всё время"] = "all time",
        ["сервер"] = "server",
        ["сервера"] = "servers",
        ["серверов"] = "servers",
        ["день"] = "day",
        ["дня"] = "days",
        ["дней"] = "days",
        ["час"] = "hour",
        ["часа"] = "hours",
        ["часов"] = "hours",
        ["никогда"] = "never",
        ["в {0:HH:mm}"] = "at {0:HH:mm}",

        ["Серверы"] = "Servers",
        ["Статистика"] = "Statistics",
        ["Настройки"] = "Settings",
        ["Добавить ключ"] = "Add key",
        ["Поиск сервера"] = "Search servers",
        ["Проверить пинг всех серверов"] = "Ping all servers",
        ["Сканировать QR"] = "Scan QR",
        ["Поделиться ключом"] = "Share key",
        ["Ключей пока нет"] = "No keys yet",
        ["Сначала добавь ключ"] = "Add a key first",
        ["Нажми на кнопку или на +, чтобы добавить ключ"] = "Press the button or + to add a key",
        ["Буфер обмена пуст: сначала скопируй ключ"] = "Clipboard is empty: copy your key first",
        ["Готово! Нажми большую кнопку, чтобы подключиться"] = "Done! Press the big button to connect",
        ["Как начать"] = "Getting started",
        ["Три шага — и VPN работает"] = "Three steps and your VPN is on",
        ["Получите ключ"] = "Get a key",
        ["Ключ выдаёт ваш VPN-сервис: обычно его присылает Telegram-бот или он есть в личном кабинете на сайте. Это ссылка вида https://… или vless://…"] =
            "Your VPN service gives you the key: usually a Telegram bot sends it, or it is in your account on the service website. It looks like a link https://… or vless://…",
        ["Добавьте его сюда"] = "Add it here",
        ["Скопируйте ключ и нажмите «Вставить ключ». Если ключ показан QR-кодом, нажмите «Сканировать QR» выше."] =
            "Copy the key and press \"Paste key\". If the key is shown as a QR code, press \"Scan QR\" above.",
        ["Подключитесь"] = "Connect",
        ["Появится список серверов. Выберите любой и нажмите большую круглую кнопку справа."] =
            "A list of servers will appear. Pick any and press the big round button on the right.",
        ["Вставить ключ"] = "Paste key",
        ["Подключаться при запуске"] = "Connect on startup",
        ["Сразу включать VPN к последнему серверу"] = "Turn on VPN to the last server right away",
        ["Запуск с Windows"] = "Start with Windows",
        ["Открываться свёрнутым в трей при входе в систему"] = "Open minimized to tray when you sign in",
        ["Tunnelka уже запущена. Её значок — рядом с часами."] = "Tunnelka is already running. Its icon is next to the clock.",
        ["Что-то пошло не так: {0}\n\nПодробности записаны в {1}"] = "Something went wrong: {0}\n\nDetails are saved in {1}",
        ["Подписка закончилась. Продлите её, чтобы VPN снова заработал."] = "The subscription has ended. Renew it to get VPN working again.",
        ["До конца подписки меньше 3 дней. Продлите её, иначе доступ будет приостановлен."] = "Less than 3 days left on the subscription. Renew it, or access will be suspended.",
        ["Продлить подписку →"] = "Renew subscription →",
        ["Подписки {0} скоро закончатся. Продлите их, иначе доступ будет приостановлен."] = "Subscriptions {0} end soon. Renew them, or access will be suspended.",
        ["Подписка «{0}» скоро закончится. Продлите её, иначе доступ будет приостановлен."] = "The subscription \"{0}\" ends soon. Renew it, or access will be suspended.",
        ["Ввести вручную"] = "Enter manually",
        ["Выход"] = "Exit",
        ["Подключиться"] = "Connect",
        ["Удалить"] = "Delete",
        ["Показать ключ"] = "Show key",
        ["Удалить ключ"] = "Delete key",
        ["Удалить ключ «{0}» и все его серверы?"] = "Delete the key \"{0}\" and all its servers?",

        ["{0} · обновлено {1} · раз в {2} ч"] = "{0} · updated {1} · every {2} h",
        ["Трафик: {0} из {1}"] = "Traffic: {0} of {1}",
        ["{0} из {1}"] = "{0} of {1}",
        ["осталось {0}"] = "{0} left",
        ["Подписка истекла"] = "Expired",
        ["Подписка без срока"] = "No expiry date",
        ["Подписка истекла {0:dd.MM.yyyy}"] = "Expired on {0:dd.MM.yyyy}",
        ["Истекает {0:dd.MM.yyyy} · осталось {1}"] = "Expires {0:dd.MM.yyyy} · {1} left",

        ["Прокси"] = "Proxy",
        ["Подключено"] = "Connected",
        ["Правила"] = "Rules",
        ["Режим списка"] = "List mode",
        ["Выбери сервер"] = "Choose a server",
        ["Обновить подписку"] = "Update subscription",
        ["Проверка пинга"] = "Check ping",
        ["Пинг {0} мс"] = "Ping {0} ms",
        ["Сервер не ответил"] = "Server did not respond",
        ["Авто"] = "Auto",
        ["Самый быстрый сервер по пингу"] = "Fastest server by ping",
        ["Ищу самый быстрый сервер…"] = "Looking for the fastest server…",
        ["Ни один сервер не ответил"] = "No server responded",
        ["Ключ не распознан"] = "Key not recognized",
        ["Подписок нет: добавь её через +"] = "No subscriptions: add one with +",
        ["Подписка обновлена"] = "Subscription updated",
        ["Не удалось обновить подписку"] = "Could not update the subscription",
        ["QR-код не найден"] = "QR code not found",
        ["QR-код на экране не найден. Выбери картинку с QR-кодом"] = "No QR code on screen. Choose an image with a QR code",
        ["Картинки|*.png;*.jpg;*.jpeg;*.bmp;*.gif"] = "Images|*.png;*.jpg;*.jpeg;*.bmp;*.gif",
        ["Нет подписок, чтобы поделиться"] = "No subscriptions to share",

        ["Добавить"] = "Add",
        ["Ключ сервера (vless, vmess, trojan, ss, hysteria2, tuic) или ключ подписки"] = "Server key (vless, vmess, trojan, ss, hysteria2, tuic) or subscription key",
        ["vless://...  или  https://..."] = "vless://...  or  https://...",
        ["Вставить из буфера"] = "Paste from clipboard",
        ["Буфер обмена пуст"] = "Clipboard is empty",
        ["Отмена"] = "Cancel",
        ["Отсканируй камерой на новом устройстве"] = "Scan with the camera on your new device",
        ["Копировать"] = "Copy",
        ["Скопировано"] = "Copied",
        ["Закрыть"] = "Close",

        ["Загрузка"] = "Download",
        ["Отдача"] = "Upload",
        ["Скорость за {0}"] = "Speed for {0}",
        ["Подключись, чтобы увидеть трафик"] = "Connect to see traffic",
        ["Через VPN за {0}"] = "Through VPN for {0}",
        ["Напрямую за {0}"] = "Direct for {0}",
        ["Всего за {0}"] = "Total for {0}",
        ["Сбросить"] = "Reset",
        ["Сбросить всю статистику трафика?"] = "Reset all traffic statistics?",

        ["Интерфейс"] = "Interface",
        ["Тема, масштаб и язык"] = "Theme, scale and language",
        ["Тёмная тема"] = "Dark theme",
        ["Мягкие тёмные цвета"] = "Soft dark colors",
        ["Масштаб интерфейса"] = "Interface scale",
        ["Ctrl + колесо мыши, Ctrl и +/−, Ctrl+0"] = "Ctrl + mouse wheel, Ctrl and +/−, Ctrl+0",
        ["Язык"] = "Language",
        ["Режим"] = "Mode",
        ["Скорость в окне"] = "Speed in window",
        ["Как часто обновлять"] = "How often to update",
        ["Подписки при запуске"] = "Subscriptions on startup",
        ["Обновлять все подписки при открытии приложения"] = "Update all subscriptions when the app opens",
        ["Пинг при запуске"] = "Ping on startup",
        ["Проверять все серверы при открытии приложения"] = "Check all servers when the app opens",
        ["Маршрутизация"] = "Routing",
        ["Какие сайты идут напрямую, через VPN или в блок"] = "Which sites go direct, through VPN or are blocked",
        ["Журнал"] = "Log",
        ["Сообщения приложения и Xray"] = "App and Xray messages",
        ["Очистить"] = "Clear",

        ["Пинг"] = "Ping",
        ["Тип пинга"] = "Ping type",
        ["Реальный (via proxy)"] = "Real (via proxy)",
        ["Быстрый (TCP)"] = "Fast (TCP)",
        ["Реальный: запрос идёт через сам сервер, как при работе VPN. Делается два запроса, берётся лучший. Нерабочий сервер покажет n/a."] =
            "Real: the request goes through the server itself, just like VPN traffic. Two requests are made and the best one counts. A broken server shows n/a.",
        ["Быстрый: проверяет только, открыт ли порт сервера. Мгновенно, но может показать пинг у сервера, через который VPN не работает."] =
            "Fast: only checks whether the server port is open. Instant, but may show ping for a server where VPN does not work.",
        ["Тестовый адрес для реального пинга"] = "Test address for real ping",
        ["Сбросить адрес"] = "Reset address",

        ["Напрямую - использование без VPN\nЧерез VPN - использование через VPN\nБлок - полная блокировка трафика"] =
            "Direct - use without VPN\nThrough VPN - use through VPN\nBlock - block all traffic",
        ["Программы (*.exe)|*.exe"] = "Programs (*.exe)|*.exe",
        ["Выбери программу"] = "Choose a program",

        ["Выбор приложения"] = "Choose an app",
        ["Выберите приложение"] = "Choose an app",
        ["Поиск по имени или пути..."] = "Search by name or path...",
        ["Приложения"] = "Apps",
        ["Выбрать"] = "Choose",

        ["Добавлено серверов: {0}"] = "Servers added: {0}",
        ["Не нашёл поддерживаемых ключей (vless, vmess, trojan, ss, hysteria2, tuic)"] = "No supported keys found (vless, vmess, trojan, ss, hysteria2, tuic)",
        ["Подключено к {0}"] = "Connected to {0}",
        ["Отключено"] = "Disconnected",
        ["Правила применены"] = "Rules applied",
        ["Переподключить"] = "Reconnect",
        ["Правила изменены. Они заработают после переподключения"] = "Rules changed. They take effect after reconnecting",
        ["Ядро VPN завершилось. Причина обычно видна в строках выше"] = "The VPN core stopped. The reason is usually in the lines above",
        ["Режим TUN: через VPN идёт весь трафик"] = "TUN mode: all traffic goes through VPN",
        ["Режим прокси: через VPN идут браузер и программы"] = "Proxy mode: the browser and apps go through VPN",
        ["Не найден {0}"] = "{0} not found",
        ["Не найден {0}\n\nСкачай sing-box-windows-amd64.zip на github.com/SagerNet/sing-box/releases и положи sing-box.exe в папку core рядом с xray.exe."] =
            "{0} not found\n\nDownload sing-box-windows-amd64.zip from github.com/SagerNet/sing-box/releases and put sing-box.exe into the core folder next to xray.exe.",
        ["Для режима TUN нужны права администратора. Перезапустить Tunnelka от имени администратора?"] =
            "TUN mode needs administrator rights. Restart Tunnelka as administrator?",
        ["Перезапуск отменён: {0}"] = "Restart canceled: {0}",

        ["Обновляю подписку"] = "Updating subscription",
        ["{0}: серверов {1}"] = "{0}: {1} servers",
        ["Ошибка подписки: {0}"] = "Subscription error: {0}",
        ["Порт {0} занят другой программой (например, Happ или v2rayN), беру {1}"] = "Port {0} is used by another app (for example Happ or v2rayN), using {1}",
        ["Порты: SOCKS5 127.0.0.1:{0}, HTTP 127.0.0.1:{1}"] = "Ports: SOCKS5 127.0.0.1:{0}, HTTP 127.0.0.1:{1}",
        ["Не удалось запустить xray: {0}"] = "Could not start xray: {0}",
        ["TUN включён"] = "TUN enabled",
        ["sing-box сразу завершился, код {0}"] = "sing-box exited right away, code {0}",
        ["Адаптер TUN не появился за 10 секунд. Его может блокировать антивирус или другой VPN"] = "The TUN adapter did not appear within 10 seconds. An antivirus or another VPN may be blocking it",
        ["Не удалось запустить TUN: {0}"] = "Could not start TUN: {0}",
        ["Системный прокси включён"] = "System proxy enabled",
        ["Системный прокси выключен"] = "System proxy disabled",
        ["Не удалось изменить системный прокси: {0}"] = "Could not change the system proxy: {0}",
        ["Не удалось сохранить настройки: {0}"] = "Could not save settings: {0}",
        ["Не удалось определить путь к программе"] = "Could not find the program path",
        ["Не удалось открыть настройки прокси Windows"] = "Could not open Windows proxy settings",
        ["Протокол {0} не поддерживается"] = "Protocol {0} is not supported",
        ["Это не ключ сервера"] = "This is not a server key",
        ["В ключе нет порта"] = "The key has no port",
        ["В ключе нет пароля"] = "The key has no password",
        ["VPN выключен"] = "VPN off",
        ["{0} мс"] = "{0} ms",
        ["Версия {0}"] = "Version {0}",
        ["Все версии"] = "All versions",
        ["Горячая клавиша"] = "Hotkey",
        ["Доступна версия {0}"] = "Version {0} is available",
        ["Загрузка {0}%"] = "Downloading {0}%",
        ["Загрузка и отдача, каждую секунду"] = "Download and upload, every second",
        ["Задержка через VPN, каждую секунду"] = "Latency through VPN, every second",
        ["Масштаб надписей оверлея"] = "Overlay text scale",
        ["Можно включить и здесь, без горячей клавиши"] = "You can also turn it on here, without the hotkey",
        ["Нажмите клавиши…"] = "Press keys…",
        ["Нажмите на поле, затем нужные клавиши"] = "Click the field, then press the keys",
        ["Нажмите, чтобы проверить новую версию"] = "Click to check for a new version",
        ["Не удалось обновить: {0}"] = "Update failed: {0}",
        ["Не удалось проверить: {0}"] = "Check failed: {0}",
        ["О приложении"] = "About",
        ["Обновления"] = "Updates",
        ["Оверлей"] = "Overlay",
        ["Подключение"] = "Connecting",
        ["Пинг и скорость поверх игр и окон"] = "Ping and speed on top of games and windows",
        ["Показать оверлей"] = "Show overlay",
        ["Показывать и скрывать оверлей поверх всех окон"] = "Show and hide the overlay on top of all windows",
        ["Положение"] = "Position",
        ["Потеря пакетов"] = "Packet loss",
        ["Проверить"] = "Check",
        ["Проверяю…"] = "Checking…",
        ["Размер"] = "Size",
        ["Сколько проверок до сервера не дошло за последние 10 секунд"] = "Share of checks to the server that failed in the last 10 seconds",
        ["Скорость"] = "Speed",
        ["Сочетание клавиш"] = "Key combination",
        ["Страница загрузок на GitHub"] = "Downloads page on GitHub",
        ["У вас последняя версия {0}"] = "You have the latest version {0}",
        ["Угол экрана"] = "Screen corner",
        ["ЧТО ПОКАЗЫВАТЬ"] = "WHAT TO SHOW",
        ["Это сочетание занято другой программой, выберите другое"] = "This combination is used by another app, choose another",
        ["мс"] = "ms",
        ["потери {0}%"] = "loss {0}%",
        ["Доступна новая версия"] = "A new version is available",
        ["Tunnelka {0}. Скачать и установить сейчас?"] = "Tunnelka {0}. Download and install now?",
        ["Да"] = "Yes",
        ["Нет"] = "No",
        ["В ответе нет серверов"] = "the response has no servers",
        ["не удалось прочитать ответ сервера"] = "could not read the server response",
        ["нет связи с сервером подписки"] = "cannot reach the subscription server",
        ["сервер подписки не ответил вовремя"] = "the subscription server timed out",
        ["сервер подписки ответил ошибкой {0}"] = "the subscription server returned error {0}",
        ["Kill switch"] = "Kill switch",
        ["Kill switch включён: без VPN интернет заблокирован"] = "Kill switch is on: internet is blocked without VPN",
        ["Kill switch выключен: интернет снова работает без VPN"] = "Kill switch is off: internet works without VPN again",
        ["Служба Tunnelka не отвечает"] = "Tunnelka service is not responding",
        ["Kill switch: служба Tunnelka не включила блокировку"] = "Kill switch: Tunnelka service did not turn on the block",
        ["Kill switch не включился, подробности в журнале"] = "Kill switch did not turn on, see the log",
        ["Kill switch не включился: {0}"] = "Kill switch did not turn on: {0}",
        ["Kill switch остался включённым после сбоя, поэтому интернет может не работать. Перезапустить Tunnelka от имени администратора, чтобы снять блокировку?"] = "Kill switch stayed on after a crash, so the internet may not work. Restart Tunnelka as administrator to remove the block?",
        ["Kill switch: не удалось прочитать настройки брандмауэра Windows"] = "Kill switch: could not read Windows Firewall settings",
        ["VPN отключился, kill switch заблокировал интернет. Переподключитесь или выключите kill switch в «Расширенное»."] = "VPN disconnected and the kill switch blocked the internet. Reconnect or turn the kill switch off in Advanced.",
        ["VPN упал — интернет заблокирован. Нажми кнопку, чтобы переподключиться"] = "VPN dropped — internet is blocked. Press the button to reconnect",
        ["sing-box не запустил {0}, код {1}"] = "sing-box did not start {0}, code {1}",
        ["Адаптер TUN создан: {0}"] = "TUN adapter created: {0}",
        ["Блокирует интернет, если VPN упал (режим TUN)"] = "Blocks the internet if VPN drops (TUN mode)",
        ["Для {0} нужен sing-box.exe в папке core"] = "{0} needs sing-box.exe in the core folder",
        ["Напрямую подписка не загрузилась, пробую через VPN"] = "Subscription did not load directly, trying through VPN",
        ["Не удалось снять kill switch: {0}"] = "Could not remove the kill switch: {0}",
        ["TUN — весь трафик компьютера"] = "TUN — all computer traffic",
        ["Расширенное"] = "Advanced",
        ["Режим туннеля, kill switch, действия при запуске"] = "Tunnel mode, kill switch, startup actions",
        ["+ Программа"] = "+ App",
        ["+ Файл .exe"] = "+ .exe file",
        ["Правила для программ надёжно работают в режиме TUN"] = "App rules work reliably in TUN mode",
        ["Сайт или IP, например sberbank.ru"] = "Site or IP, e.g. example.com",
        ["Скачать файлы VPN?"] = "Download the VPN files?",
        ["Не хватает файлов для работы VPN: {0}. Скачать их с официальных страниц разработчиков на GitHub (около {1} МБ)? Подлинность проверяется контрольной суммой."] =
            "Some files needed for the VPN are missing: {0}. Download them from the developers' official GitHub pages (about {1} MB)? Authenticity is checked with a checksum.",
        ["Скачать"] = "Download",
        ["Не сейчас"] = "Not now",
        ["Не удалось скачать: {0}"] = "Download failed: {0}",
        ["Контрольная сумма не совпала, файл не использован"] = "Checksum mismatch, the file was not used",
        ["В архиве нет файла {0}"] = "The archive has no file {0}",
        ["Сначала добавь программу или сайт"] = "Add an app or a site first",
        ["Список пуст. Добавь программу или сайт"] = "The list is empty. Add an app or a site",
        ["Адаптер TUN не создан: мешает другой VPN ({0}). Закройте его и переподключитесь"] = "TUN adapter was not created: another VPN is in the way ({0}). Close it and reconnect",
        ["Для режима TUN нужны права администратора"] = "TUN mode needs administrator rights",
        ["Работает другой VPN в режиме TUN ({0}). Он может мешать адаптеру Tunnelka"] = "Another VPN is running in TUN mode ({0}). It may interfere with the Tunnelka adapter",
        ["Трафик ядра идёт напрямую через адаптер {0}, мимо другого VPN"] = "Core traffic goes directly through adapter {0}, bypassing the other VPN",
        ["VPN только для выбранных"] = "VPN only for selected",
        ["Без VPN для выбранных"] = "Without VPN for selected",
        ["ВЫБРАННЫЕ ПРОГРАММЫ И САЙТЫ"] = "SELECTED APPS AND SITES",
        ["Всё через VPN"] = "Everything via VPN",
        ["Программы и сайты из списка идут напрямую, остальное через VPN"] = "Apps and sites from the list go direct, the rest goes through VPN",
        ["Список не действует, весь трафик идёт через VPN"] = "The list is not used, all traffic goes through VPN",
        ["Через VPN идут только программы и сайты из списка"] = "Only apps and sites from the list go through VPN"
    };
}
