namespace VpnClient;

public static class L
{
    public static bool English { get; private set; }

    public static void Use(string language) => English = language == "en";

    public static string T(string russian) =>
        English && En.TryGetValue(russian, out var english) ? english : russian;

    public static string F(string russian, params object[] args) => string.Format(T(russian), args);

    private static readonly Dictionary<string, string> En = new()
    {
        ["/с"] = "/s",
        ["Б"] = "B",
        ["КБ"] = "KB",
        ["МБ"] = "MB",
        ["ГБ"] = "GB",
        ["ТБ"] = "TB",
        ["{0} с"] = "{0} s",
        ["{0} мин"] = "{0} min",
        ["{0} ч"] = "{0} h",
        ["3 мин"] = "3 min",
        ["10 мин"] = "10 min",
        ["30 мин"] = "30 min",
        ["1 ч"] = "1 h",
        ["3 ч"] = "3 h",
        ["5 ч"] = "5 h",
        ["24 ч"] = "24 h",
        ["Всё"] = "All",
        ["всё время"] = "all time",
        ["сервер"] = "server",
        ["сервера"] = "servers",
        ["серверов"] = "servers",
        ["день"] = "day",
        ["дня"] = "days",
        ["дней"] = "days",
        ["час"] = "hour",
        ["часа"] = "hours",
        ["часов"] = "hours",
        ["никогда"] = "never",
        ["в {0:HH:mm}"] = "at {0:HH:mm}",

        ["Серверы"] = "Servers",
        ["Статистика"] = "Statistics",
        ["Настройки"] = "Settings",
        ["Добавить ключ"] = "Add key",
        ["Поиск сервера"] = "Search servers",
        ["Проверить пинг всех серверов"] = "Ping all servers",
        ["Сканировать QR"] = "Scan QR",
        ["Поделиться ключом"] = "Share key",
        ["Ключей пока нет"] = "No keys yet",
        ["Сначала добавь ключ"] = "Add a key first",
        ["Нажми на кнопку или на +, чтобы добавить ключ"] = "Press the button or + to add a key",
        ["Буфер обмена пуст: сначала скопируй ключ"] = "Clipboard is empty: copy your key first",
        ["Готово! Нажми большую кнопку, чтобы подключиться"] = "Done! Press the big button to connect",
        ["Как начать"] = "Getting started",
        ["Три шага — и VPN работает"] = "Three steps and your VPN is on",
        ["Получите ключ"] = "Get a key",
        ["Ключ выдаёт ваш VPN-сервис: обычно его присылает Telegram-бот или он есть в личном кабинете на сайте. Это ссылка вида https://… или vless://…"] =
            "Your VPN service gives you the key: usually a Telegram bot sends it, or it is in your account on the service website. It looks like a link https://… or vless://…",
        ["Добавьте его сюда"] = "Add it here",
        ["Скопируйте ключ и нажмите «Вставить ключ». Если ключ показан QR-кодом, нажмите «Сканировать QR» выше."] =
            "Copy the key and press \"Paste key\". If the key is shown as a QR code, press \"Scan QR\" above.",
        ["Подключитесь"] = "Connect",
        ["Появится список серверов. Выберите любой и нажмите большую круглую кнопку справа."] =
            "A list of servers will appear. Pick any and press the big round button on the right.",
        ["Вставить ключ"] = "Paste key",
        ["Ввести вручную"] = "Enter manually",
        ["Выход"] = "Exit",
        ["Подключиться"] = "Connect",
        ["Удалить"] = "Delete",
        ["Показать ключ"] = "Show key",
        ["Удалить ключ"] = "Delete key",
        ["Удалить ключ «{0}» и все его серверы?"] = "Delete the key \"{0}\" and all its servers?",

        ["{0} · обновлено {1} · раз в {2} ч"] = "{0} · updated {1} · every {2} h",
        ["Трафик: {0} из {1}"] = "Traffic: {0} of {1}",
        ["Подписка без срока"] = "No expiry date",
        ["Подписка истекла {0:dd.MM.yyyy}"] = "Expired on {0:dd.MM.yyyy}",
        ["Истекает {0:dd.MM.yyyy} · осталось {1}"] = "Expires {0:dd.MM.yyyy} · {1} left",

        ["Прокси"] = "Proxy",
        ["ПОДКЛЮЧЕНО"] = "CONNECTED",
        ["ОТКЛЮЧЕНО"] = "DISCONNECTED",
        ["Выбери сервер"] = "Choose a server",
        ["Обновить подписку"] = "Update subscription",
        ["Проверка пинга"] = "Check ping",
        ["Пинг {0} мс"] = "Ping {0} ms",
        ["Сервер не ответил"] = "Server did not respond",
        ["Ключ не распознан"] = "Key not recognized",
        ["Подписок нет: добавь её через +"] = "No subscriptions: add one with +",
        ["Подписка обновлена"] = "Subscription updated",
        ["Не удалось обновить подписку"] = "Could not update the subscription",
        ["QR-код не найден"] = "QR code not found",
        ["QR-код на экране не найден. Выбери картинку с QR-кодом"] = "No QR code on screen. Choose an image with a QR code",
        ["Картинки|*.png;*.jpg;*.jpeg;*.bmp;*.gif"] = "Images|*.png;*.jpg;*.jpeg;*.bmp;*.gif",
        ["Нет подписок, чтобы поделиться"] = "No subscriptions to share",

        ["Добавить"] = "Add",
        ["Ключ сервера (vless, vmess, trojan, ss) или ключ подписки"] = "Server key (vless, vmess, trojan, ss) or subscription key",
        ["vless://...  или  https://..."] = "vless://...  or  https://...",
        ["Вставить из буфера"] = "Paste from clipboard",
        ["Буфер обмена пуст"] = "Clipboard is empty",
        ["Отмена"] = "Cancel",
        ["Отсканируй камерой на новом устройстве"] = "Scan with the camera on your new device",
        ["Копировать"] = "Copy",
        ["Скопировано"] = "Copied",
        ["Закрыть"] = "Close",

        ["Загрузка"] = "Download",
        ["Отдача"] = "Upload",
        ["Скорость за {0}"] = "Speed for {0}",
        ["Подключись, чтобы увидеть трафик"] = "Connect to see traffic",
        ["Через VPN за {0}"] = "Through VPN for {0}",
        ["Напрямую за {0}"] = "Direct for {0}",
        ["Всего за {0}"] = "Total for {0}",
        ["Сбросить"] = "Reset",
        ["Сбросить всю статистику трафика?"] = "Reset all traffic statistics?",

        ["Интерфейс"] = "Interface",
        ["Тема, масштаб и язык"] = "Theme, scale and language",
        ["Тёмная тема"] = "Dark theme",
        ["Мягкие тёмные цвета"] = "Soft dark colors",
        ["Масштаб интерфейса"] = "Interface scale",
        ["Ctrl + колесо мыши, Ctrl и +/−, Ctrl+0"] = "Ctrl + mouse wheel, Ctrl and +/−, Ctrl+0",
        ["Язык"] = "Language",
        ["Режим"] = "Mode",
        ["Режим туннелирования"] = "Tunneling mode",
        ["Скорость в окне"] = "Speed in window",
        ["Как часто обновлять"] = "How often to update",
        ["Подписки при запуске"] = "Subscriptions on startup",
        ["Обновлять все подписки при открытии приложения"] = "Update all subscriptions when the app opens",
        ["Пинг при запуске"] = "Ping on startup",
        ["Проверять все серверы при открытии приложения"] = "Check all servers when the app opens",
        ["Маршрутизация"] = "Routing",
        ["Какие сайты идут напрямую, через VPN или в блок"] = "Which sites go direct, through VPN or are blocked",
        ["Журнал"] = "Log",
        ["Сообщения приложения и Xray"] = "App and Xray messages",
        ["Очистить"] = "Clear",

        ["Пинг"] = "Ping",
        ["Тип пинга"] = "Ping type",
        ["Реальный (via proxy)"] = "Real (via proxy)",
        ["Быстрый (TCP)"] = "Fast (TCP)",
        ["Реальный: запрос идёт через сам сервер, как при работе VPN. Делается два запроса, берётся лучший. Нерабочий сервер покажет n/a."] =
            "Real: the request goes through the server itself, just like VPN traffic. Two requests are made and the best one counts. A broken server shows n/a.",
        ["Быстрый: проверяет только, открыт ли порт сервера. Мгновенно, но может показать пинг у сервера, через который VPN не работает."] =
            "Fast: only checks whether the server port is open. Instant, but may show ping for a server where VPN does not work.",
        ["Тестовый адрес для реального пинга"] = "Test address for real ping",
        ["Сбросить адрес"] = "Reset address",

        ["Домены или IP через запятую"] = "Domains or IPs, comma separated",
        ["Напрямую"] = "Direct",
        ["Через VPN"] = "Through VPN",
        ["Блок"] = "Block",
        ["Блокировать"] = "Block",
        ["Напрямую - использование без VPN\nЧерез VPN - использование через VPN\nБлок - полная блокировка трафика"] =
            "Direct - use without VPN\nThrough VPN - use through VPN\nBlock - block all traffic",
        ["Правила проверяются сверху вниз. Всё остальное идёт через VPN."] = "Rules are checked top to bottom. Everything else goes through VPN.",
        ["Российские сайты напрямую"] = "Russian sites direct",
        ["Процесс"] = "Process",
        ["Файл .exe"] = ".exe file",
        ["Программы (*.exe)|*.exe"] = "Programs (*.exe)|*.exe",
        ["Выбери программу"] = "Choose a program",
        ["Правил пока нет"] = "No rules yet",
        ["{0} (файл)"] = "{0} (file)",
        ["{0} (процесс)"] = "{0} (process)",

        ["Выбор приложения"] = "Choose an app",
        ["Выберите приложение"] = "Choose an app",
        ["Поиск по имени или пути..."] = "Search by name or path...",
        ["Приложения"] = "Apps",
        ["Выбрать"] = "Choose",

        ["Добавлено серверов: {0}"] = "Servers added: {0}",
        ["Не нашёл поддерживаемых ключей (vless, vmess, trojan, ss)"] = "No supported keys found (vless, vmess, trojan, ss)",
        ["Подключено к {0}"] = "Connected to {0}",
        ["Отключено"] = "Disconnected",
        ["Правила применены"] = "Rules applied",
        ["Ядро VPN завершилось. Причина обычно видна в строках выше"] = "The VPN core stopped. The reason is usually in the lines above",
        ["Режим TUN: через VPN идёт весь трафик"] = "TUN mode: all traffic goes through VPN",
        ["Режим прокси: через VPN идут браузер и программы"] = "Proxy mode: the browser and apps go through VPN",
        ["Не найден {0}"] = "{0} not found",
        ["Не найден {0}\n\nСкачай sing-box-windows-amd64.zip на github.com/SagerNet/sing-box/releases и положи sing-box.exe в папку core рядом с xray.exe."] =
            "{0} not found\n\nDownload sing-box-windows-amd64.zip from github.com/SagerNet/sing-box/releases and put sing-box.exe into the core folder next to xray.exe.",
        ["Для режима TUN нужны права администратора. Перезапустить Tunnelka от имени администратора?"] =
            "TUN mode needs administrator rights. Restart Tunnelka as administrator?",
        ["Перезапуск отменён: {0}"] = "Restart canceled: {0}",

        ["Обновляю подписку"] = "Updating subscription",
        ["{0}: серверов {1}"] = "{0}: {1} servers",
        ["Ошибка подписки: {0}"] = "Subscription error: {0}",
        ["Порт {0} занят другой программой (например, Happ или v2rayN), беру {1}"] = "Port {0} is used by another app (for example Happ or v2rayN), using {1}",
        ["Порты: SOCKS5 127.0.0.1:{0}, HTTP 127.0.0.1:{1}"] = "Ports: SOCKS5 127.0.0.1:{0}, HTTP 127.0.0.1:{1}",
        ["Не удалось запустить xray: {0}"] = "Could not start xray: {0}",
        ["TUN включён"] = "TUN enabled",
        ["Не удалось запустить TUN: {0}"] = "Could not start TUN: {0}",
        ["Системный прокси включён"] = "System proxy enabled",
        ["Системный прокси выключен"] = "System proxy disabled",
        ["Не удалось изменить системный прокси: {0}"] = "Could not change the system proxy: {0}",
        ["Не удалось сохранить настройки: {0}"] = "Could not save settings: {0}",
        ["Не удалось определить путь к программе"] = "Could not find the program path",
        ["Не удалось открыть настройки прокси Windows"] = "Could not open Windows proxy settings",
        ["Протокол {0} не поддерживается"] = "Protocol {0} is not supported",
        ["Это не ключ сервера"] = "This is not a server key",
        ["В ключе нет порта"] = "The key has no port",
        ["В ключе нет пароля"] = "The key has no password"
    };
}
